/**
 * Error Patterns Module
 *
 * Shared constants for error detection patterns used by both the runtime
 * error handlers and the generated inline error handler code.
 *
 * This module eliminates duplication between detectPathViolation()/
 * extractPathFromError()/extractOperationFromError() and the self-contained
 * inline handler generated by generateInlineErrorHandler().
 */

/** Error codes indicating path violations */
export const PATH_VIOLATION_CODES = ["PATH_VIOLATION", "SYMLINK_VIOLATION", "NotCapable"] as const;

/** Error messages indicating path violations */
export const PATH_VIOLATION_MESSAGES = [
  "is outside allowed directories",
  "outside allowed directories",
  "Requires read access to",
  "Requires write access to",
] as const;

/** Regex to extract path from Deno-style errors: Requires read/write access to "path" */
export const DENO_PATH_REGEX = /Requires (?:read|write) access to "([^"]+)"/;

/** Regex to extract path from SafeShell-style errors: Path/Symlink 'path' */
export const SAFESH_PATH_REGEX = /(?:Path|Symlink) '([^']+)'/;

/** Regex to extract real path from symlink violations: points to 'path' */
export const SYMLINK_REAL_PATH_REGEX = /points to '([^']+)'/;

/** Message indicating write operation */
export const WRITE_ACCESS_MESSAGE = "Requires write access to";

/** Command failure message patterns (not path violations) */
export const COMMAND_FAILURE_MESSAGES = [
  "Pipeline failed: upstream command exited with code",
  "command exited with code",
  "Command failed with exit code",
] as const;
